from __future__ import annotations

ETF_DATABASE = {
    "QQQI": {"name": "NEOS Nasdaq-100 High Income ETF", "issuer": "NEOS", "strategy": "Index covered call", "exposure": "Nasdaq-100", "frequency": "Monthly", "expense_ratio": 0.0068, "risk_band": "High", "roc_note": "May include return of capital; verify tax notices."},
    "JEPQ": {"name": "JPMorgan Nasdaq Equity Premium Income ETF", "issuer": "JPMorgan", "strategy": "Active equity + ELN option income", "exposure": "Nasdaq-oriented large cap", "frequency": "Monthly", "expense_ratio": 0.0035, "risk_band": "Medium-High", "roc_note": "Tax character varies; verify annual tax reporting."},
    "SPYI": {"name": "NEOS S&P 500 High Income ETF", "issuer": "NEOS", "strategy": "Index covered call", "exposure": "S&P 500", "frequency": "Monthly", "expense_ratio": 0.0068, "risk_band": "High", "roc_note": "May include return of capital; verify tax notices."},
    "JEPI": {"name": "JPMorgan Equity Premium Income ETF", "issuer": "JPMorgan", "strategy": "Active equity + ELN option income", "exposure": "U.S. large cap", "frequency": "Monthly", "expense_ratio": 0.0035, "risk_band": "Medium", "roc_note": "Tax character varies; verify annual tax reporting."},
    "QYLD": {"name": "Global X Nasdaq 100 Covered Call ETF", "issuer": "Global X", "strategy": "Full index covered call", "exposure": "Nasdaq-100", "frequency": "Monthly", "expense_ratio": 0.0060, "risk_band": "High", "roc_note": "Distributions may include return of capital."},
    "XYLD": {"name": "Global X S&P 500 Covered Call ETF", "issuer": "Global X", "strategy": "Full index covered call", "exposure": "S&P 500", "frequency": "Monthly", "expense_ratio": 0.0060, "risk_band": "High", "roc_note": "Distributions may include return of capital."},
    "RYLD": {"name": "Global X Russell 2000 Covered Call ETF", "issuer": "Global X", "strategy": "Full index covered call", "exposure": "Russell 2000", "frequency": "Monthly", "expense_ratio": 0.0060, "risk_band": "Very High", "roc_note": "Distributions may include return of capital."},
    "FEPI": {"name": "REX FANG & Innovation Equity Premium Income ETF", "issuer": "REX Shares", "strategy": "Individual-stock covered calls", "exposure": "FANG and innovation stocks", "frequency": "Weekly", "expense_ratio": 0.0065, "risk_band": "Very High", "roc_note": "High distributions may include return of capital."},
    "AIPI": {"name": "REX AI Equity Premium Income ETF", "issuer": "REX Shares", "strategy": "Individual-stock covered calls", "exposure": "AI-related equities", "frequency": "Weekly", "expense_ratio": 0.0065, "risk_band": "Very High", "roc_note": "High distributions may include return of capital."},
    "GPIQ": {"name": "Goldman Sachs Nasdaq-100 Premium Income ETF", "issuer": "Goldman Sachs", "strategy": "Dynamic option overlay", "exposure": "Nasdaq-100", "frequency": "Monthly", "expense_ratio": 0.0029, "risk_band": "Medium-High", "roc_note": "Verify tax character in annual fund documents."},
    "GPIX": {"name": "Goldman Sachs S&P 500 Premium Income ETF", "issuer": "Goldman Sachs", "strategy": "Dynamic option overlay", "exposure": "S&P 500", "frequency": "Monthly", "expense_ratio": 0.0029, "risk_band": "Medium", "roc_note": "Verify tax character in annual fund documents."},
    "IWMI": {"name": "NEOS Russell 2000 High Income ETF", "issuer": "NEOS", "strategy": "Index covered call", "exposure": "Russell 2000", "frequency": "Monthly", "expense_ratio": 0.0068, "risk_band": "Very High", "roc_note": "May include return of capital; verify tax notices."},
    "XDTE": {"name": "Roundhill S&P 500 0DTE Covered Call Strategy ETF", "issuer": "Roundhill", "strategy": "0DTE index covered call", "exposure": "S&P 500", "frequency": "Weekly", "expense_ratio": 0.0097, "risk_band": "Very High", "roc_note": "Fund states distributions may exceed income and gains and be return of capital."},
    "QDTE": {"name": "Roundhill Innovation-100 0DTE Covered Call Strategy ETF", "issuer": "Roundhill", "strategy": "0DTE index covered call", "exposure": "Innovation-100 / Nasdaq-like", "frequency": "Weekly", "expense_ratio": 0.0097, "risk_band": "Very High", "roc_note": "Fund states distributions may exceed income and gains and be return of capital."},
    "RDTE": {"name": "Roundhill Small Cap 0DTE Covered Call Strategy ETF", "issuer": "Roundhill", "strategy": "0DTE index covered call", "exposure": "U.S. small cap", "frequency": "Weekly", "expense_ratio": 0.0097, "risk_band": "Very High", "roc_note": "Fund states distributions may exceed income and gains and be return of capital."},
    "DIVO": {"name": "Amplify CWP Enhanced Dividend Income ETF", "issuer": "Amplify", "strategy": "Dividend equity + selective covered calls", "exposure": "U.S. large cap dividend stocks", "frequency": "Monthly", "expense_ratio": 0.0056, "risk_band": "Medium", "roc_note": "Verify tax character in annual fund documents."},
    "SVOL": {"name": "Simplify Volatility Premium ETF", "issuer": "Simplify", "strategy": "Short-volatility premium with hedges", "exposure": "VIX futures and options", "frequency": "Monthly", "expense_ratio": 0.0100, "risk_band": "Very High", "roc_note": "Not a conventional covered-call ETF; tax character may be complex."},
    "ISPY": {"name": "ProShares S&P 500 High Income ETF", "issuer": "ProShares", "strategy": "Daily covered-call income", "exposure": "S&P 500", "frequency": "Monthly", "expense_ratio": 0.0055, "risk_band": "High", "roc_note": "Verify tax character in annual fund documents."},
    "IQQQ": {"name": "ProShares Nasdaq-100 High Income ETF", "issuer": "ProShares", "strategy": "Daily covered-call income", "exposure": "Nasdaq-100", "frequency": "Monthly", "expense_ratio": 0.0055, "risk_band": "High", "roc_note": "Verify tax character in annual fund documents."},
    "SPYT": {"name": "Defiance S&P 500 Target Income ETF", "issuer": "Defiance", "strategy": "Options-based target income", "exposure": "S&P 500", "frequency": "Monthly", "expense_ratio": 0.0099, "risk_band": "Very High", "roc_note": "Target distributions are not guaranteed and may include return of capital."},
    "QQQT": {"name": "Defiance Nasdaq-100 Target Income ETF", "issuer": "Defiance", "strategy": "Options-based target income", "exposure": "Nasdaq-100", "frequency": "Monthly", "expense_ratio": 0.0099, "risk_band": "Very High", "roc_note": "Target distributions are not guaranteed and may include return of capital."},
    "YBTC": {"name": "Roundhill Bitcoin Covered Call Strategy ETF", "issuer": "Roundhill", "strategy": "Bitcoin-futures exposure + covered calls", "exposure": "Bitcoin-related", "frequency": "Weekly", "expense_ratio": 0.0095, "risk_band": "Extreme", "roc_note": "Crypto-linked and derivatives risks; distributions may include return of capital."},
    "YETH": {"name": "Roundhill Ether Covered Call Strategy ETF", "issuer": "Roundhill", "strategy": "Ether exposure + covered calls", "exposure": "Ethereum-related", "frequency": "Weekly", "expense_ratio": 0.0095, "risk_band": "Extreme", "roc_note": "Crypto-linked and derivatives risks; distributions may include return of capital."},
}

DEFAULT_TICKERS = list(ETF_DATABASE.keys())
